### ISSUE TITLE
Unable to set vision range for other Senses

### ISSUE THREAD

**Issue by JamzTheMan** [JDCalvert/FVTT-PF2e-Rules-Based-NPC-Vision#8]
There are some NPC's, like some oozes (e.g. Blood Ooze) that have senses set to `motion sense 60 feet, no vision`

Ideally, I would give them dark vision of 60' then set the Perfect Vision monochrome to some other tint as a reminder that it was motion of tremor or some other sense...

If the creature doesn't have a darkvision, maybe a reg ex lookup like `\w+ sense ([0-9]+) feet` could set Bright vision to x instead of 1000?

Or let us override the 1000 feet per creature (only set to 1000 if 0 or null? or something?  I have an Ooze fight coming up that had a mix of darkvision and "no sight" but other "vision" in the senses that I need to know if they can "see" said targets.

**Comment by JDCalvert** [comment]
I've had a little play around with this, and the problem with other senses is that they tend to be situational. Low-light vision and darkvision are easy because Foundry has lighting built-in. There's nothing to set whether a creature is on the same surface as someone with tremoursense, or whether they moved within the last round for motionsense, are alive for lifesense etc.

The aim of this module is to replicate the vision rules that normally only apply to PCs to also work for NPCs. Right now, the system has no automation for any of these except the light-based senses. Therefore, I'm afraid that I'm going to have to declare this out of scope for the module until such functionality is made available for PCs in the system.
